-- ==============================================================================
-- SCHEMA SUPABASE (POSTGRESQL) - CIAK MANIA MAGAZINE
-- Puoi incollare questo script direttamente nel "SQL Editor" del tuo progetto Supabase!
-- ==============================================================================

-- 1. UTENTI & REDATTORI
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL,
  avatar VARCHAR(5) NOT NULL,
  bio TEXT DEFAULT NULL,
  profile_image TEXT DEFAULT NULL
);

-- 2. CATEGORIE
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  color VARCHAR(20) NOT NULL,
  "desc" TEXT NOT NULL
);

-- 3. ARTICOLI & POST
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  rating NUMERIC(3,1) DEFAULT NULL,
  image TEXT DEFAULT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  date VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL,
  tags TEXT DEFAULT NULL,
  keyword VARCHAR(100) DEFAULT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  "metaDesc" TEXT DEFAULT NULL,
  views INT DEFAULT 0,
  comments INT DEFAULT 0,
  author VARCHAR(100) NOT NULL,
  technical_judgment TEXT DEFAULT NULL
);

-- 4. COMMENTI
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "articleTitle" VARCHAR(255) NOT NULL,
  author VARCHAR(100) NOT NULL,
  text TEXT NOT NULL,
  date VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL
);

-- 5. MESSAGGI
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  excerpt TEXT NOT NULL,
  text TEXT NOT NULL,
  date VARCHAR(50) NOT NULL,
  folder VARCHAR(20) DEFAULT 'inbox',
  unread BOOLEAN DEFAULT TRUE,
  starred BOOLEAN DEFAULT FALSE
);

-- 6. AUDIT LOGS
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" VARCHAR(100) NOT NULL,
  action VARCHAR(255) NOT NULL,
  target VARCHAR(255) NOT NULL,
  time VARCHAR(50) NOT NULL
);

-- 7. SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "siteName" VARCHAR(255) NOT NULL,
  "siteDesc" TEXT NOT NULL
);

-- 8. MEDIA
CREATE TABLE IF NOT EXISTS public.media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  name VARCHAR(100) NOT NULL
);

-- 9. NOTIFICHE
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  is_read BOOLEAN DEFAULT FALSE
);

-- 10. CLASSIFICHE & RANKINGS 3D
CREATE TABLE IF NOT EXISTS public.rankings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(50) DEFAULT 'film',
  period VARCHAR(50) DEFAULT 'settimanale',
  status VARCHAR(20) DEFAULT 'pubblicata',
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 11. VOCI / ITEMS CLASSIFICHE
CREATE TABLE IF NOT EXISTS public.ranking_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ranking_id BIGINT REFERENCES public.rankings(id) ON DELETE CASCADE,
  movie_id BIGINT DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  year VARCHAR(20) DEFAULT NULL,
  genre VARCHAR(100) DEFAULT NULL,
  rating VARCHAR(20) DEFAULT NULL,
  image TEXT DEFAULT NULL,
  description TEXT DEFAULT NULL,
  position INT NOT NULL,
  previous_position INT DEFAULT NULL,
  movement VARCHAR(20) DEFAULT 'same',
  badge VARCHAR(50) DEFAULT NULL,
  link_url TEXT DEFAULT NULL,
  reviews_count VARCHAR(50) DEFAULT NULL
);

-- SEED INIZIALE UTENTI
INSERT INTO public.users (username, password, name, role, avatar) VALUES
('admin', 'admin123', 'Leila Cimarelli', 'Admin', 'LC'),
('editor', 'editor123', 'Redattore Ciak', 'Editor', 'RC')
ON CONFLICT (username) DO NOTHING;

-- SEED SETTINGS
INSERT INTO public.settings (id, "siteName", "siteDesc") VALUES
(1, 'Ciak Mania Magazine', 'La tua dose quotidiana di grande cinema ed esclusive.')
ON CONFLICT (id) DO NOTHING;

-- SEED CATEGORIE OBBLIGATORIE
INSERT INTO public.categories (id, name, slug, color, "desc") VALUES
(1, 'Film', 'film', '#e50914', 'Tutti i film e le ultime novita cinematografiche'),
(2, 'Serie TV', 'serie-tv', '#0070f3', 'Recensioni e notizie sulle serie TV e streaming'),
(3, 'Recensioni', 'recensioni', '#ffb400', 'Tutte le recensioni con voto e giudizio critico'),
(4, 'Articoli', 'articoli', '#10b981', 'Approfondimenti, speciali ed interviste'),
(5, 'Classifiche', 'classifiche', '#ffa305', 'Articoli in classifica'),
(6, 'News', 'news', '#601f5e', 'Le news inerenti al mondo del cinema')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  color = EXCLUDED.color,
  "desc" = EXCLUDED."desc";

-- ABILITA ACCESSO DI LETTURA PUBBLICO TRAMITE SUPABASE RLS (Opzionale / Consigliato per le API REST di Supabase)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow update access on users" ON public.users FOR UPDATE USING (true);

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access on articles" ON public.articles FOR SELECT USING (true);
CREATE POLICY "Allow public insert on articles" ON public.articles FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on articles" ON public.articles FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on articles" ON public.articles FOR DELETE USING (true);

ALTER TABLE public.rankings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access on rankings" ON public.rankings FOR SELECT USING (true);
CREATE POLICY "Allow public insert on rankings" ON public.rankings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on rankings" ON public.rankings FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on rankings" ON public.rankings FOR DELETE USING (true);

ALTER TABLE public.ranking_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access on ranking_items" ON public.ranking_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert on ranking_items" ON public.ranking_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on ranking_items" ON public.ranking_items FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on ranking_items" ON public.ranking_items FOR DELETE USING (true);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access on categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow public insert on categories" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on categories" ON public.categories FOR UPDATE USING (true);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access on comments" ON public.comments FOR ALL USING (true);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access on messages" ON public.messages FOR ALL USING (true);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow public update access on settings" ON public.settings FOR UPDATE USING (true);

ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access on media" ON public.media FOR ALL USING (true);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all access on notifications" ON public.notifications FOR ALL USING (true);
